### ISSUE TITLE
About cpu

### ISSUE THREAD

**Issue by DanaHan** [PLChinDev/Dell-Precision-5510-Mojave#1]
After update to use VirtualSMC. I can not read cpu fans speed info from HW HWsmc HWsmc2 iStat TG Pro. When run smc -f to show fans info. It said total 0 fans in the system. And fans run heavy. when use 10.15 version. The cpu temperature is very high. What can I do? Can I read fans info and control fans speed to decrease the temperature?

**Comment by PLChinDev** [comment]
Apologies. I just saw this open issue. I have updated repo a few times. Please pull new files and advise if issue still persists.
